# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('message_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('SPAM', 'Spam'), ('ABUSE', 'Abuse'), ('SELF_HARM_RISK', 'Self harm risk'), ('HARASSMENT', 'Harassment'), ('ILLEGAL', 'Illegal'), ('PRIVACY', 'Privacy'), ('PAYMENT_FRAUD', 'Payment fraud'), ('RATE_LIMIT', 'Rate limit'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=10)),
                ('rule_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.BooleanField(db_index=True, default=False)),
                ('action_note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'safety_safetyevent',
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('NONE', 'None'), ('THROTTLE', 'Throttle'), ('LIMITED', 'Limited'), ('BLOCKED', 'Blocked'), ('SHADOW', 'Shadow')], db_index=True, default='NONE', max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('internal_note', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_msgs_per_minute', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_msgs_per_day', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)])),
                ('block_initiation', models.BooleanField(db_index=True, default=False)),
                ('block_media', models.BooleanField(db_index=True, default=False)),
                ('block_purchases', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'safety_userrestriction',
            },
        ),
        migrations.CreateModel(
            name='BlockedPhrase',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phrase', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, default='OTHER', max_length=20)),
                ('severity', models.CharField(db_index=True, default='LOW', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'safety_blockedphrase',
                'indexes': [models.Index(fields=['is_active', 'event_type'], name='safety_bloc_is_acti_40d320_idx'), models.Index(fields=['phrase'], name='safety_bloc_phrase_e20f8d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('phrase', ''), _negated=True), name='safety_blockedphrase_phrase_nonempty')],
            },
        ),
    ]
