# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrestriction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['event_type', 'created_at'], name='safety_safe_event_t_cb1b12_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['severity', 'created_at'], name='safety_safe_severit_a0fd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['user', 'created_at'], name='safety_safe_user_id_4805c1_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['conversation_id'], name='safety_safe_convers_d885bb_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['message_id'], name='safety_safe_message_a3691c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(fields=['level'], name='safety_user_level_33ec99_idx'),
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(fields=['expires_at'], name='safety_user_expires_ac0fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(fields=['block_initiation'], name='safety_user_block_i_0d628e_idx'),
        ),
    ]
