# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('language_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('block_reason', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone', models.CharField(blank=True, db_index=True, default='Asia/Tehran', max_length=64)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('initiation_opt_in', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_user',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prefs', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reply_length', models.CharField(choices=[('VERY_SHORT', 'Very short'), ('SHORT', 'Short'), ('MEDIUM', 'Medium')], default='SHORT', max_length=16)),
                ('question_tolerance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('tone', models.CharField(choices=[('VERY_PLAIN', 'Very plain'), ('PLAIN', 'Plain'), ('WARM', 'Warm')], default='VERY_PLAIN', max_length=16)),
                ('emotional_distance', models.FloatField(default=0.6, help_text='Higher = more distance, less emotional language.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('verbosity', models.FloatField(default=0.3, help_text='Higher = longer responses (but still bounded by contract).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prefers_initiation', models.BooleanField(default=True)),
                ('initiation_cooldown_hours', models.PositiveSmallIntegerField(default=36)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('total_user_messages', models.PositiveIntegerField(default=0)),
                ('total_bot_replies', models.PositiveIntegerField(default=0)),
                ('last_profile_refresh_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('style_rules', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'users_userprefs',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_blocked'], name='users_user_is_acti_ca0520_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_seen_at'], name='users_user_last_se_8aae7b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_username'], name='users_user_telegra_496936_idx'),
        ),
    ]
