# Generated by Django 5.2.9 on 2026-01-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_assigned_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("UNKNOWN", "Unknown"),
                ],
                db_index=True,
                default="UNKNOWN",
                max_length=8,
            ),
        ),
    ]
