# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('coins', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('currency', models.CharField(db_index=True, default='IRR', max_length=8)),
                ('price_amount', models.BigIntegerField(help_text='Price in minor units (e.g., Rials)', validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('tag', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'db_table': 'billing_coinpack',
            },
        ),
        migrations.CreateModel(
            name='CoinTxn',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.BigIntegerField(help_text='Signed coin delta. +credit / -debit')),
                ('reason', models.CharField(choices=[('PURCHASE_CREDIT', 'Purchase credit'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('PROMO_CREDIT', 'Promo credit'), ('REFUND_CREDIT', 'Refund credit'), ('CHAT_REPLY_DEBIT', 'Chat reply debit'), ('TOOLING_DEBIT', 'Tooling debit'), ('REVERSAL_DEBIT', 'Reversal debit'), ('NOTE', 'Note')], db_index=True, max_length=32)),
                ('ref_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('ref_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('balance_after', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_cointxn',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CREDITED', 'Credited'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=12)),
                ('gateway', models.CharField(choices=[('ZARINPAL', 'Zarinpal'), ('ZIBAL', 'Zibal'), ('PAYIR', 'Pay.ir'), ('MANUAL', 'Manual'), ('SANDBOX', 'Sandbox')], db_index=True, default='SANDBOX', max_length=16)),
                ('currency', models.CharField(db_index=True, default='IRR', max_length=8)),
                ('amount', models.BigIntegerField(help_text='Charged amount in minor units (e.g., Rials)', validators=[django.core.validators.MinValueValidator(0)])),
                ('coins', models.PositiveIntegerField(help_text='Coins to credit for this purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('gateway_authority', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('gateway_ref_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('gateway_card_pan', models.CharField(blank=True, default='', max_length=32)),
                ('gateway_raw', models.JSONField(blank=True, default=dict)),
                ('credit_txn_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'billing_purchase',
            },
        ),
    ]
