# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.BigIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_frozen', models.BooleanField(db_index=True, default=False)),
                ('freeze_reason', models.CharField(blank=True, default='', max_length=255)),
                ('last_txn_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'billing_wallet',
            },
        ),
        migrations.AddIndex(
            model_name='coinpack',
            index=models.Index(fields=['is_active', 'sort_order'], name='billing_coi_is_acti_32c060_idx'),
        ),
        migrations.AddIndex(
            model_name='coinpack',
            index=models.Index(fields=['currency'], name='billing_coi_currenc_29da43_idx'),
        ),
        migrations.AddField(
            model_name='cointxn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_txns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='billing.coinpack'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['balance'], name='billing_wal_balance_831d14_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_frozen'], name='billing_wal_is_froz_1054cf_idx'),
        ),
        migrations.AddIndex(
            model_name='cointxn',
            index=models.Index(fields=['user', 'created_at'], name='billing_coi_user_id_9f5390_idx'),
        ),
        migrations.AddIndex(
            model_name='cointxn',
            index=models.Index(fields=['reason', 'created_at'], name='billing_coi_reason_ac029a_idx'),
        ),
        migrations.AddIndex(
            model_name='cointxn',
            index=models.Index(fields=['ref_type', 'ref_id'], name='billing_coi_ref_typ_c81211_idx'),
        ),
        migrations.AddConstraint(
            model_name='cointxn',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='billing_cointxn_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='cointxn',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='billing_cointxn_unique_user_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'created_at'], name='billing_pur_user_id_a4ec6d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', 'created_at'], name='billing_pur_status_ac8d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['gateway', 'gateway_authority'], name='billing_pur_gateway_96e30a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['gateway_ref_id'], name='billing_pur_gateway_cd9306_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_ref_id', ''), _negated=True), fields=('gateway', 'gateway_ref_id'), name='billing_purchase_unique_gateway_ref'),
        ),
    ]
