# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=12)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_user_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_bot_reply_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('has_unread_bot_message', models.BooleanField(db_index=True, default=False)),
                ('topic_hint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'chat_conversation',
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('GEMINI', 'Gemini'), ('OTHER', 'Other')], db_index=True, default='OPENAI', max_length=16)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('RATE_LIMIT', 'Rate limit')], db_index=True, default='OK', max_length=16)),
                ('error_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempt', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('token_in', models.PositiveIntegerField(default=0)),
                ('token_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('prompt_meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'chat_llmcalllog',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot'), ('SYSTEM', 'System')], db_index=True, max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('telegram_update_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('token_in', models.PositiveIntegerField(default=0)),
                ('token_out', models.PositiveIntegerField(default=0)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('seq', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
    ]
