# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='trigger_message',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'USER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_llm_calls', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'bot', 'status'], name='chat_conver_user_id_084f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_activity_at'], name='chat_conver_status_f6e6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'last_activity_at'], name='chat_conver_user_id_3e28a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'bot'), name='chat_unique_active_conversation_per_user_bot'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'seq'], name='chat_messag_convers_c897c6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role', 'created_at'], name='chat_messag_role_35f48a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['telegram_update_id'], name='chat_messag_telegra_1a51ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='chat_unique_message_seq_per_conversation'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_message_id', None), _negated=True), fields=('conversation', 'telegram_message_id'), name='chat_unique_telegram_message_id_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_llmcal_convers_b5017a_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['provider', 'model', 'created_at'], name='chat_llmcal_provide_339073_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['status', 'created_at'], name='chat_llmcal_status_6fc3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['request_id'], name='chat_llmcal_request_cd04b1_idx'),
        ),
    ]
