# Generated by Django 5.2.9 on 2026-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="memory_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
