# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=48)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_prompt_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('base_prompt_text', models.TextField(blank=True, default='')),
                ('default_language', models.CharField(blank=True, db_index=True, default='fa', max_length=12)),
                ('avatar_key', models.CharField(blank=True, default='', max_length=64)),
                ('max_output_chars', models.PositiveSmallIntegerField(default=350)),
                ('max_questions_per_reply', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'persona_bot',
            },
        ),
        migrations.CreateModel(
            name='BotUserState',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('familiarity', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('trust', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('emotional_closeness', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_pref_verbosity', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_pref_questions', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_user_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_bot_reply_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_initiation_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_user_messages', models.PositiveIntegerField(default=0)),
                ('total_bot_replies', models.PositiveIntegerField(default=0)),
                ('shared_silence', models.PositiveIntegerField(default=0, help_text='Count of times user did not reply after bot msg.')),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('style_rules', models.JSONField(blank=True, default=dict)),
                ('initiation_opt_in', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'persona_botuserstate',
            },
        ),
        migrations.CreateModel(
            name='MemoryFragment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('TOPIC', 'Topic'), ('PREFERENCE', 'Preference'), ('FACT_SOFT', 'Soft fact'), ('RELATIONSHIP', 'Relationship cue')], db_index=True, default='TOPIC', max_length=16)),
                ('topic', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('hint_text', models.CharField(help_text='Vague hint text; no quotes; no exact details.', max_length=220)),
                ('confidence', models.FloatField(db_index=True, default=0.55, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('decay_rate', models.FloatField(default=0.015, help_text='Daily decay rate (rough).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('times_reinforced', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'persona_memoryfragment',
            },
        ),
        migrations.CreateModel(
            name='PromptSnippet',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=96)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'persona_promptsnippet',
            },
        ),
        migrations.CreateModel(
            name='BotIdentity',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identity', serialize=False, to='persona.bot')),
                ('core_tone', models.CharField(choices=[('QUIET', 'QUIET'), ('PLAIN', 'PLAIN'), ('WARM', 'WARM'), ('DRY', 'DRY')], db_index=True, default='QUIET', max_length=16)),
                ('background_seed', models.CharField(db_index=True, default='UNKNOWN_PAST', max_length=32)),
                ('self_confidence', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('openness', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('talkativeness', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('emotional_clarity', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('memory_strength', models.FloatField(default=0.6, help_text='Higher means better recall; never perfect.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('memory_noise', models.FloatField(default=0.15, help_text='Higher means more mistakes/ambiguity in recall hints.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avoids_advice', models.BooleanField(default=True)),
                ('avoids_therapy_tone', models.BooleanField(default=True)),
                ('avoids_omniscience', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'persona_botidentity',
            },
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['is_active', 'code'], name='persona_bot_is_acti_aa5275_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['display_name'], name='persona_bot_display_01f191_idx'),
        ),
        migrations.AddField(
            model_name='botuserstate',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='persona.bot'),
        ),
    ]
