# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botuserstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryfragment',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_fragments', to='persona.botuserstate'),
        ),
        migrations.AddIndex(
            model_name='promptsnippet',
            index=models.Index(fields=['is_active', 'key'], name='persona_pro_is_acti_aaa1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsnippet',
            index=models.Index(fields=['version'], name='persona_pro_version_fed2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='botidentity',
            index=models.Index(fields=['core_tone'], name='persona_bot_core_to_b92af8_idx'),
        ),
        migrations.AddIndex(
            model_name='botidentity',
            index=models.Index(fields=['background_seed'], name='persona_bot_backgro_2788a0_idx'),
        ),
        migrations.AddIndex(
            model_name='botuserstate',
            index=models.Index(fields=['bot', 'user'], name='persona_bot_bot_id_e7cca2_idx'),
        ),
        migrations.AddIndex(
            model_name='botuserstate',
            index=models.Index(fields=['user', 'last_user_message_at'], name='persona_bot_user_id_9f790a_idx'),
        ),
        migrations.AddIndex(
            model_name='botuserstate',
            index=models.Index(fields=['bot', 'last_initiation_at'], name='persona_bot_bot_id_049638_idx'),
        ),
        migrations.AddConstraint(
            model_name='botuserstate',
            constraint=models.UniqueConstraint(fields=('bot', 'user'), name='persona_unique_bot_user_state'),
        ),
        migrations.AddIndex(
            model_name='memoryfragment',
            index=models.Index(fields=['state', 'is_active', 'confidence'], name='persona_mem_state_i_a93f69_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryfragment',
            index=models.Index(fields=['topic', 'confidence'], name='persona_mem_topic_794e64_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryfragment',
            index=models.Index(fields=['last_seen_at'], name='persona_mem_last_se_1cac9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryfragment',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='persona_mem_conf_0_1'),
        ),
    ]
