# Generated by Django 5.2.9 on 2026-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botidentity",
            name="identity_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="botuserstate",
            name="relationship_memory",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
