# Generated by Django 5.2.9 on 2026-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0003_botidentity_identity_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="gender",
            field=models.CharField(blank=True, db_index=True, default="", max_length=8),
        ),
    ]
