# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitiationEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('SCHEDULER', 'Scheduler'), ('MANUAL', 'Manual'), ('RECOVERY', 'Recovery')], db_index=True, default='SCHEDULER', max_length=16)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed'), ('ACKED', 'Acked')], db_index=True, default='PLANNED', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('message_text', models.CharField(blank=True, default='', max_length=220)),
                ('telegram_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('user_replied', models.BooleanField(db_index=True, default=False)),
                ('user_replied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('error_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'automation_initiationevent',
            },
        ),
        migrations.CreateModel(
            name='InitiationRule',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('cooldown_hours', models.PositiveSmallIntegerField(default=36)),
                ('max_per_day', models.PositiveSmallIntegerField(default=1)),
                ('max_per_week', models.PositiveSmallIntegerField(default=3)),
                ('min_familiarity', models.FloatField(default=0.1)),
                ('min_trust', models.FloatField(default=0.05)),
                ('allowed_start_hour', models.PositiveSmallIntegerField(default=10)),
                ('allowed_end_hour', models.PositiveSmallIntegerField(default=23)),
                ('max_chars', models.PositiveSmallIntegerField(default=180)),
                ('allow_question', models.BooleanField(default=False)),
                ('templates', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'automation_initiationrule',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('INITIATION_SWEEP', 'Initiation sweep'), ('MEMORY_DECAY', 'Memory decay'), ('HOUSEKEEPING', 'Housekeeping')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('RUNNING', 'Running')], db_index=True, default='OK', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'automation_scheduledjob',
            },
        ),
    ]
