# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiationevent',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiation_events', to='persona.bot'),
        ),
        migrations.AddField(
            model_name='initiationevent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiation_events', to='persona.botuserstate'),
        ),
    ]
