# Generated by Django 5.2.9 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0002_initial'),
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiationevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiationrule',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initiation_rule', to='persona.bot'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['job_type', 'created_at'], name='automation__job_typ_e6521e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['status', 'created_at'], name='automation__status_e5c0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='initiationevent',
            index=models.Index(fields=['status', 'created_at'], name='automation__status_5bcfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='initiationevent',
            index=models.Index(fields=['user', 'created_at'], name='automation__user_id_612afb_idx'),
        ),
        migrations.AddIndex(
            model_name='initiationevent',
            index=models.Index(fields=['bot', 'created_at'], name='automation__bot_id_574fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='initiationevent',
            index=models.Index(fields=['scheduled_for'], name='automation__schedul_41778b_idx'),
        ),
        migrations.AddIndex(
            model_name='initiationevent',
            index=models.Index(fields=['sent_at'], name='automation__sent_at_14631b_idx'),
        ),
        migrations.AddConstraint(
            model_name='initiationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('state', 'idempotency_key'), name='automation_unique_initiation_idem_per_state'),
        ),
        migrations.AddIndex(
            model_name='initiationrule',
            index=models.Index(fields=['enabled'], name='automation__enabled_09a2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='initiationrule',
            index=models.Index(fields=['cooldown_hours'], name='automation__cooldow_bf4f47_idx'),
        ),
    ]
